#ifndef __HELP_H_INCLUDED_
#define __HELP_H_INCLUDED_

const char * const HELP_TEXT =
"<loader> [-h]\n"
"        -h, --help - show help\n"
"\n"
"<loader> [-i,-t,-m] <serial-port>\n"
"        -i, --info - connect to the device and show bootloader information\n"
"\n"
"<loader> -p [-t,-m,-f,-e,-r] <serial-port> <firmware-file-name>\n"
"        -p, --program - program the firmware into the device with verification\n"
"\n"
"<loader> -v [-t,-m] <serial-port> <firmware-file-name>\n"
"        -v, --verify - verify if the device has the specified firmware\n"
"\n"
"<loader> -l [-t,-m,-a,-s] <serial-port> <firmware-file-name>\n"
"        -l, --load - download the current device firmware to the file\n"
"\n"
"<loader> -e [-t,-m,-f] <serial-port>\n"
"        -e, --erase - erase all device memory excluding the bootloader\n"
"\n"
"Options:\n"
"        -t=<secs>, --timeout=<secs> - connection timeout in seconds\n"
"                                      (0 - infinite, default: 0)\n"
"        -m=<model>, --model=<model> - check if the device has the specified\n"
"                                      model (default: no check)\n"
"        -f, --force - force overwrite the memory even if it has same content\n"
"                      (default: no)\n"
"        -e, --erase - erase memory areas not specified in the firmware file\n"
"                      (default: no)\n"
"        -r, --no-run - do not run the firmware after programing (default: run)\n"
"        -a, -all - include the bootloader into the firmware image\n"
"                   (default: no)\n"
"        -s, --no-smart - do not exclude unprogrammed memory areas from the\n"
"                         firmware image (default: exclude)\n"
"\n"
"Examples:\n"
"        <loader> COM3 - show bootloader information\n"
"        <loader> -p -e -r COM3 firmware.hex - erase and program the device\n"
"                 with the \"firmware.hex\" file, do not run the firmware\n"
"        <loader> -v COM3 firmware.hex - verify the device firmware\n"
"        <loader> -l -a COM3 firmware.hex - download the device firmware to the\n"
"                 \"firmware.hex\" file with the bootloader\n"
"        <loader> -e COM3 - erase the device memory excluding the bootloader\n";

#endif // !__HELP_H_INCLUDED_
